In [4]:
# importimg all the important libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import sklearn
import pickle 


In [2]:
# reading the csv file of top movies 

data=pd.read_csv("top10K-TMDB-movies.csv")

In [3]:
data.head()

id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14   
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15   
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20   

   vote_average  vote_count  
0           8.7       21862  
1           8.7        3731  
2           8.7       16280  
3           8.6       12959  
4           8.6        9811

In [5]:
# checking of the null values present in the dataset 
data.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

There are two olumns consists of null values that are Genre that has 3null values and Overview has 13 null values which can be neglected 

In [6]:
data.shape 

(10000, 9)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 10000 non-null  int64  
 1   title              10000 non-null  object 
 2   genre              9997 non-null   object 
 3   original_language  10000 non-null  object 
 4   overview           9987 non-null   object 
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object 
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64  
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB


In [8]:
data.dtypes

id                     int64
title                 object
genre                 object
original_language     object
overview              object
popularity           float64
release_date          object
vote_average         float64
vote_count             int64
dtype: object

From the following dataset we can see that we don't need the columns like "release_date" , "vote_average","vote_count" ,"original_language"


In [11]:
# we can drop the columns which are not needed 

movie=data[["id" ,"title","genre","overview"]]

In [12]:
movie.head()

id                        title                 genre  \
0    278     The Shawshank Redemption           Drama,Crime   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance   
2    238                The Godfather           Drama,Crime   
3    424             Schindler's List     Drama,History,War   
4    240       The Godfather: Part II           Drama,Crime   

                                            overview  
0  Framed in the 1940s for the double murder of h...  
1  Raj is a rich, carefree, happy-go-lucky second...  
2  Spanning the years 1945 to 1955, a chronicle o...  
3  The true story of how businessman Oskar Schind...  
4  In the continuing saga of the Corleone crime f...

Now we can merge the two columns i.e. genre and overview for further process named it as "review"

In [13]:
movie["review"]=movie["genre"]+movie["overview"]

C:\Users\hp\AppData\Local\Temp\ipykernel_4116\602271654.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie["review"]=movie["genre"]+movie["overview"]


In [14]:
movie.head()

id                        title                 genre  \
0    278     The Shawshank Redemption           Drama,Crime   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance   
2    238                The Godfather           Drama,Crime   
3    424             Schindler's List     Drama,History,War   
4    240       The Godfather: Part II           Drama,Crime   

                                            overview  \
0  Framed in the 1940s for the double murder of h...   
1  Raj is a rich, carefree, happy-go-lucky second...   
2  Spanning the years 1945 to 1955, a chronicle o...   
3  The true story of how businessman Oskar Schind...   
4  In the continuing saga of the Corleone crime f...   

                                              review  
0  Drama,CrimeFramed in the 1940s for the double ...  
1  Comedy,Drama,RomanceRaj is a rich, carefree, h...  
2  Drama,CrimeSpanning the years 1945 to 1955, a ...  
3  Drama,History,WarThe true story of how busines...  
4  Drama,CrimeIn the continuing saga of the Corle...

Now I don't need these two columns anymore i.e. "genre" and "overview"

In [17]:
movie.drop(["genre","overview"],axis=1,inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_4116\2759562197.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie.drop(["genre","overview"],axis=1,inplace=True)


In [18]:
movie.head()

id                        title  \
0    278     The Shawshank Redemption   
1  19404  Dilwale Dulhania Le Jayenge   
2    238                The Godfather   
3    424             Schindler's List   
4    240       The Godfather: Part II   

                                              review  
0  Drama,CrimeFramed in the 1940s for the double ...  
1  Comedy,Drama,RomanceRaj is a rich, carefree, h...  
2  Drama,CrimeSpanning the years 1945 to 1955, a ...  
3  Drama,History,WarThe true story of how busines...  
4  Drama,CrimeIn the continuing saga of the Corle...

Now we are going to implement feature extraction on it we have to convert the text data of review into feature vector so that we can feed it on our model

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv=CountVectorizer(max_features=10000, stop_words="english")

In [21]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [22]:
vector=cv.fit_transform(movie["review"].values.astype("U")).toarray()

In [23]:
vector.shape

(10000, 10000)

In [24]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

Now we hvae to find the similarity between the vectors and recommend the movies on the basis of similarity 

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
similarity=cosine_similarity(vector)

In [27]:
similarity

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]])

In [31]:
movie[movie["title"]=="The Shawshank Redemption"].index[0]

0

In [32]:
similarity[0]

array([1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
       0.03798686])

In [33]:
sorted(list(enumerate(similarity[0])))

[(0, 1.0),
 (1, 0.06253053994807226),
 (2, 0.05802588531856595),
 (3, 0.04103049699311092),
 (4, 0.06154574548966637),
 (5, 0.04222003309207491),
 (6, 0.03892494720807615),
 (7, 0.055749467333806056),
 (8, 0.029854071701326604),
 (9, 0.0),
 (10, 0.06963106238227915),
 (11, 0.0),
 (12, 0.0),
 (13, 0.09231861823449955),
 (14, 0.03289758474798845),
 (15, 0.02686076546751268),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (20, 0.07597371763975865),
 (21, 0.04222003309207491),
 (22, 0.0),
 (23, 0.03481553119113957),
 (24, 0.04222003309207491),
 (25, 0.030772872744833184),
 (26, 0.08444006618414981),
 (27, 0.052486388108147805),
 (28, 0.10241831129983785),
 (29, 0.03553345272593508),
 (30, 0.037113480951260276),
 (31, 0.03289758474798845),
 (32, 0.07422696190252055),
 (33, 0.03481553119113957),
 (34, 0.05372153093502536),
 (35, 0.03892494720807615),
 (36, 0.10497277621629561),
 (37, 0.0),
 (38, 0.09231861823449955),
 (39, 0.0),
 (40, 0.0),
 (41, 0.06154574548966637),
 (42, 0.0),
 (43, 0.0

In [35]:
distance = sorted(list(enumerate(similarity[0])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(movie.iloc[i[0]].title)

The Shawshank Redemption
Anything for Her
The Woodsman
The Getaway
Pusher II


Now we'r gonna make a function named it as recommend and pass movie name so that it can search the related movies only

In [36]:
def recommend(movie_name):
    index=movie[movie["title"]==movie_name].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(movie.iloc[i[0]].title)

In [37]:
recommend("Iron Man")

Iron Man
Mazinger Z: Infinity
Justice League Dark
Iron Man 3
The Colony


We will save the model for the further use using library in python named as pickle

In [39]:
pickle.dump(movie,open("movie_list.pkl","wb"))

pickle.dump(similarity,open("similarity.pkl","wb"))

In [40]:
pickle.load(open("movie_list.pkl","rb"))

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 review  
0     Drama,CrimeFramed in the 1940s for the double ...  
1     Comedy,Drama,RomanceRaj is a rich, carefree, h...  
2     Drama,CrimeSpanning the years 1945 to 1955, a ...  
3     Drama,History,WarThe true story of how busines...  
4     Drama,CrimeIn the continuing saga of the Corle...  
...                                                 ...  
9995  Action,Adventure,FantasyThe story follows the ...  
9996  Action,TV Movie,Science Fiction,Comedy,Adventu...  
9997  Action,Science Fiction,WarDuring World War II,...  
9998  Adventure,Fantasy,Action,DramaA man named Farm...  
9999  Thriller,Action,CrimeSeeking justice for his p...  

[10000 rows x 3 columns]